### ISSUE TITLE
 module 'pyparsing' has no attribute 'downcaseTokens'

### ISSUE THREAD

**Issue by paulaceccon** [PAIR-code/what-if-tool#185]
IInstall:

```
!pip install pyparsing==2.4.7
!pip install --upgrade witwidget -q
```

```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_7815/70839168.py in <module>
      1 #@title Invoke What-If Tool for the data and model {display-mode: "form"}
----> 2 from witwidget.notebook.visualization import WitWidget, WitConfigBuilder
      3 
      4 num_datapoints = 5000  #@param {type: "number"}
      5 tool_height_in_px = 700  #@param {type: "number"}

/usr/local/lib/python3.9/dist-packages/witwidget/notebook/visualization.py in <module>
     25   from witwidget.notebook.colab.wit import *  # pylint: disable=wildcard-import,g-import-not-at-top
     26 else:
---> 27   from witwidget.notebook.jupyter.wit import *  # pylint: disable=wildcard-import,g-import-not-at-top
     28 
     29 

/usr/local/lib/python3.9/dist-packages/witwidget/notebook/jupyter/wit.py in <module>
     24 from traitlets import Unicode
     25 from traitlets import Set
---> 26 from witwidget.notebook import base
     27 
     28 

/usr/local/lib/python3.9/dist-packages/witwidget/notebook/base.py in <module>
     15 import base64
     16 import json
---> 17 import googleapiclient.discovery
     18 import os
     19 import logging

/usr/local/lib/python3.9/dist-packages/googleapiclient/discovery.py in <module>
     40 
     41 # Third-party imports
---> 42 import httplib2
     43 import uritemplate
     44 import google.api_core.client_options

/usr/local/lib/python3.9/dist-packages/httplib2/__init__.py in <module>
     50     # idea is to have soft-dependency on any compatible module called socks
     51     from . import socks
---> 52 from . import auth
     53 from .error import *
     54 from .iri2uri import iri2uri

/usr/local/lib/python3.9/dist-packages/httplib2/auth.py in <module>
     18 
     19 quoted_string = pp.dblQuotedString.copy().setName("quoted-string").setParseAction(unquote)
---> 20 auth_param_name = token.copy().setName("auth-param-name").addParseAction(pp.downcaseTokens)
     21 auth_param = auth_param_name + pp.Suppress("=") + (quoted_string | token)
     22 params = pp.Dict(pp.delimitedList(pp.Group(auth_param)))

AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'
```

**Comment by queengooborg** [comment]
Came here after running into the same issue but in web2py.  This issue seems to come from an [incompatibility in `httplib2`](https://github.com/httplib2/httplib2/issues/207).  After upgrading to v0.20.2 of `httplib2`, I am no longer running into this problem.

Hope this helps!

**Comment by HishamKhdair** [comment]
> Came here after running into the same issue but in web2py. This issue seems to come from an [incompatibility in `httplib2`](https://github.com/httplib2/httplib2/issues/207). After upgrading to v0.20.2 of `httplib2`, I am no longer running into this problem.
> 
> Hope this helps!

Thanks. That really helped 👍

**Comment by amitpandey2194** [comment]
> Came here after running into the same issue but in web2py. This issue seems to come from an [incompatibility in `httplib2`](https://github.com/httplib2/httplib2/issues/207). After upgrading to v0.20.2 of `httplib2`, I am no longer running into this problem.
> 
> Hope this helps!

Or by downgrading to 0.19.0. That also worked

**Comment by alishaneogi98** [comment]
Thanks This also work for me. By running this command only  - pip install httplib2. This will automatically downgrade the pyparsing to 2.4.7 version.

pip install httplib2

Requirement already satisfied: httplib2 in c:\programdata\anaconda3\lib\site-packages (0.20.1)
Collecting pyparsing<3,>=2.4.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pyparsing
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.0.4
    Uninstalling pyparsing-3.0.4:
      Successfully uninstalled pyparsing-3.0.4
Successfully installed pyparsing-2.4.7
Note: you may need to restart the kernel to use updated packages.
